[build-system]
requires = ["scikit-build-core", "numpy"]
build-backend = "scikit_build_core.build"

[project]
name = "trustregion"
version = "1.0"
dependencies = [
    "numpy"
]
requires-python = ">=3.8"
authors = [
    {name = "Lindon Roberts", email = "lindon.roberts@unimelb.edu.au"}
]
maintainers = [
    {name = "Lindon Roberts", email = "lindon.roberts@unimelb.edu.au"}
]
description = "Trust-region subproblem solvers for nonlinear/nonconvex optimization"
readme = "README.md"
license = {text = "GPL-3.0-or-later"}
keywords = ["mathematics", "optimization"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Framework :: IPython",
    "Framework :: Jupyter",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: Unix",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics"
]

[project.optional-dependencies]
dev = ["pytest"]

[project.urls]
Homepage = "https://github.com/lindonroberts/trustregion"
Download = "https://github.com/lindonroberts/trustregion/releases/"
"Bug Tracker" = "https://github.com/lindonroberts/trustregion/issues/"
Documentation = "https://github.com/lindonroberts/trustregion"
"Source Code" = "https://github.com/lindonroberts/trustregion"